# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10 #order in which they show up

[[main]]
  name = "Projects"
  url = "/tutorial/"
  weight = 20

[[main]]
  name = "Publications"
  url = "/tutorial/"
  weight = 30

[[main]]
  name = "R"
  url = "/tutorial2/"
  weight = 40
  
#[[main]]
#  name = "Youtube Videos"
#  url = "/tutorial2/"
#  weight = 50

[[main]]
  name = "CV"
  url = "/content/files/CV.pdf"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 100








